/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 4.596003779343675, 3.081752520711041, 2.0952329578791247 };
const float ei_classifier_anom_mean[3] = { 4.125081558890444, 2.87020098172071, 2.2586195897300683 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.8936449885368347, -0.9213606715202332, -1.0548911094665527 }, 0.4533074030455766 },
	{ ( float[3] ) { -0.282134085893631, -0.038931991904973984, 2.8964056968688965 }, 0.7361646594647516 },
	{ ( float[3] ) { 0.1563042849302292, 2.7225189208984375, 1.1331571340560913 }, 0.6366084710835614 },
	{ ( float[3] ) { 1.477724552154541, -0.4796049892902374, 0.36773863434791565 }, 0.47079059062168166 },
	{ ( float[3] ) { -0.32597988843917847, 0.5577737092971802, 0.0008100905106402934 }, 0.4916762216837317 },
	{ ( float[3] ) { 2.1366448402404785, -0.0673614889383316, 0.8189782500267029 }, 0.6281718796658448 },
	{ ( float[3] ) { 1.0526211261749268, 2.6019444465637207, 0.775522768497467 }, 0.723942479899793 },
	{ ( float[3] ) { -0.57230544090271, -0.355994313955307, 1.411120891571045 }, 0.4373555700573405 },
	{ ( float[3] ) { -0.6549834609031677, -0.3815108835697174, -0.8210569620132446 }, 0.40863543395164426 },
	{ ( float[3] ) { 1.5965590476989746, 0.35028114914894104, -0.10356848686933517 }, 0.4557785778518132 },
	{ ( float[3] ) { 1.2964829206466675, -0.37826189398765564, -0.3286679983139038 }, 0.43466336483385826 },
	{ ( float[3] ) { -0.20125102996826172, 1.404172658920288, -0.03933539241552353 }, 0.5242460060195405 },
	{ ( float[3] ) { -0.36247509717941284, -0.40106314420700073, 2.0945420265197754 }, 0.8240025556155413 },
	{ ( float[3] ) { -0.5714678168296814, -0.10994413495063782, -0.7429494857788086 }, 0.3588688575698055 },
	{ ( float[3] ) { -0.38068923354148865, 0.15072210133075714, 2.1648073196411133 }, 1.005647887931708 },
	{ ( float[3] ) { 1.819551944732666, 0.5296543836593628, 0.37106072902679443 }, 0.4233836541658137 },
	{ ( float[3] ) { -0.6325485706329346, -0.33786460757255554, -0.5550335049629211 }, 0.31483100621737997 },
	{ ( float[3] ) { -0.2588914632797241, 2.9281136989593506, -0.40599289536476135 }, 0.466851117235663 },
	{ ( float[3] ) { 1.2221753597259521, 0.009369445033371449, -0.4178639352321625 }, 0.4781196227850395 },
	{ ( float[3] ) { -0.46571648120880127, -0.06565430760383606, 1.1595174074172974 }, 0.6417427095549477 },
	{ ( float[3] ) { -0.47806432843208313, 0.22126758098602295, -0.13879670202732086 }, 0.5608381023428177 },
	{ ( float[3] ) { -0.5291784405708313, -0.020902451127767563, 1.5754095315933228 }, 0.8024594102730073 },
	{ ( float[3] ) { 1.071181058883667, -0.22755302488803864, 0.43232211470603943 }, 0.47780842315872696 },
	{ ( float[3] ) { 1.5929996967315674, -0.10982880741357803, -0.4694029986858368 }, 0.4482893416467659 },
	{ ( float[3] ) { -0.16105332970619202, 2.0281736850738525, 0.6099802851676941 }, 0.6516492536355549 },
	{ ( float[3] ) { -0.6089662313461304, 0.8726818561553955, 0.42993125319480896 }, 0.32885621394644216 },
	{ ( float[3] ) { -0.6854320168495178, -0.5834718346595764, 0.9251843690872192 }, 0.5343764834793627 },
	{ ( float[3] ) { 0.03328348696231842, 0.557767927646637, 0.678409218788147 }, 0.5506743482073366 },
	{ ( float[3] ) { 1.983135461807251, 0.13071689009666443, 0.28091567754745483 }, 0.4060093122858138 },
	{ ( float[3] ) { 0.022036466747522354, 3.297816276550293, -0.2907038629055023 }, 0.6115737786584462 },
	{ ( float[3] ) { 0.3753938376903534, 1.799954891204834, 3.085679054260254 }, 0.8792310339650393 },
	{ ( float[3] ) { -0.25121089816093445, 2.241910219192505, -0.003356317989528179 }, 0.4455985009057474 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
