/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'firmware-alif.Debug+HE' 
 * Target:  'Debug+HE' 
 */

#ifndef PRE_INCLUDE_GLOBAL_H
#define PRE_INCLUDE_GLOBAL_H

/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.24.11 */
// enabling global pre includes 
        #define ETHOSU_ARCH u55


#endif /* PRE_INCLUDE_GLOBAL_H */
