/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.12.0+p48-gd3223e31
 *
 * Project: 'firmware-alif.Debug+HE' 
 * Target:  'Debug+HE' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "M55_HE.h"

/* AlifSemiconductor::Device:SOC Peripherals:GPIO@1.3.0 */
#define RTE_Drivers_GPIO   1           /* Driver GPIO */
/* AlifSemiconductor::Device:SOC Peripherals:PINCONF@1.3.0 */
#define RTE_Drivers_LL_PINCONF   1           /* Driver PinPAD and PinMux */
/* AlifSemiconductor::Device:SOC Peripherals:USART@1.3.0 */
#define RTE_Drivers_USART0   1           /* Driver UART0 */
#define RTE_Drivers_USART1   1           /* Driver UART1 */
#define RTE_Drivers_USART2   1           /* Driver UART2 */
#define RTE_Drivers_USART3   1           /* Driver UART3 */
#define RTE_Drivers_USART4   1           /* Driver UART4 */
#define RTE_Drivers_USART5   1           /* Driver UART5 */
#define RTE_Drivers_USART6   1           /* Driver UART6 */
#define RTE_Drivers_USART7   1           /* Driver UART7 */
/* AlifSemiconductor::Device:SOC Peripherals:UTIMER@1.3.0 */
#define RTE_Drivers_UTIMER   1           /* Driver UTIMER */
/* Arm::Machine Learning:NPU Support:Ethos-U Driver&Generic U55@1.24.11 */
#define RTE_ETHOS_U_CORE_DRIVER


#endif /* RTE_COMPONENTS_H */
